package an.dpr.gesclub.contracts;

import java.util.ArrayList;
import java.util.List;

import an.dpr.gesclub.domain.Municipio;

public class MunicipioContracts {

    public static final String CODIGO_PROVINCIA_ZARAGOZA = "50";
    public static final String CODIGO_INE_ZARAGOZA = "50297";

    public static List<Municipio> getMunicipiosZaragoza() {
	List<Municipio> list = new ArrayList<Municipio>();
	list.add(new Municipio("50001", "Abanto"));
	list.add(new Municipio("50002", "Acered"));
	list.add(new Municipio("50003", "Agón"));
	list.add(new Municipio("50004", "Aguarón"));
	list.add(new Municipio("50005", "Aguilón"));
	list.add(new Municipio("50006", "Ainzón"));
	list.add(new Municipio("50007", "Aladrén"));
	list.add(new Municipio("50008", "Alagón"));
	list.add(new Municipio("50009", "Alarba"));
	list.add(new Municipio("50010", "Alberite de San Juan"));
	list.add(new Municipio("50011", "Albeta"));
	list.add(new Municipio("50012", "Alborge"));
	list.add(new Municipio("50013", "Alcalá de Ebro"));
	list.add(new Municipio("50014", "Alcalá de Moncayo"));
	list.add(new Municipio("50015", "Alconchel de Ariza"));
	list.add(new Municipio("50016", "Aldehuela de Liestos"));
	list.add(new Municipio("50017", "Alfajarín"));
	list.add(new Municipio("50018", "Alfamén"));
	list.add(new Municipio("50019", "Alforque"));
	list.add(new Municipio("50020", "Alhama de Aragón"));
	list.add(new Municipio("50021", "Almochuel"));
	list.add(new Municipio("50022", "Almolda, La"));
	list.add(new Municipio("50023", "Almonacid de la Cuba"));
	list.add(new Municipio("50024", "Almonacid de la Sierra"));
	list.add(new Municipio("50025", "Almunia de Doña Godina, La"));
	list.add(new Municipio("50026", "Alpartir"));
	list.add(new Municipio("50027", "Ambel"));
	list.add(new Municipio("50028", "Anento"));
	list.add(new Municipio("50029", "Aniñón"));
	list.add(new Municipio("50030", "Añón de Moncayo"));
	list.add(new Municipio("50031", "Aranda de Moncayo"));
	list.add(new Municipio("50032", "Arándiga"));
	list.add(new Municipio("50033", "Ardisa"));
	list.add(new Municipio("50034", "Ariza"));
	list.add(new Municipio("50035", "Artieda"));
	list.add(new Municipio("50036", "Asín"));
	list.add(new Municipio("50037", "Atea"));
	list.add(new Municipio("50038", "Ateca"));
	list.add(new Municipio("50039", "Azuara"));
	list.add(new Municipio("50040", "Badules"));
	list.add(new Municipio("50041", "Bagüés"));
	list.add(new Municipio("50042", "Balconchán"));
	list.add(new Municipio("50043", "Bárboles"));
	list.add(new Municipio("50044", "Bardallur"));
	list.add(new Municipio("50045", "Belchite"));
	list.add(new Municipio("50046", "Belmonte de Gracián"));
	list.add(new Municipio("50047", "Berdejo"));
	list.add(new Municipio("50048", "Berrueco"));
	list.add(new Municipio("50901", "Biel"));
	list.add(new Municipio("50050", "Bijuesca"));
	list.add(new Municipio("50051", "Biota"));
	list.add(new Municipio("50052", "Bisimbre"));
	list.add(new Municipio("50053", "Boquiñeni"));
	list.add(new Municipio("50054", "Bordalba"));
	list.add(new Municipio("50055", "Borja"));
	list.add(new Municipio("50056", "Botorrita"));
	list.add(new Municipio("50057", "Brea de Aragón"));
	list.add(new Municipio("50058", "Bubierca"));
	list.add(new Municipio("50059", "Bujaraloz"));
	list.add(new Municipio("50060", "Bulbuente"));
	list.add(new Municipio("50061", "Bureta"));
	list.add(new Municipio("50062", "Burgo de Ebro, El"));
	list.add(new Municipio("50063", "Buste, El"));
	list.add(new Municipio("50064", "Cabañas de Ebro"));
	list.add(new Municipio("50065", "Cabolafuente"));
	list.add(new Municipio("50066", "Cadrete"));
	list.add(new Municipio("50067", "Calatayud"));
	list.add(new Municipio("50068", "Calatorao"));
	list.add(new Municipio("50069", "Calcena"));
	list.add(new Municipio("50070", "Calmarza"));
	list.add(new Municipio("50071", "Campillo de Aragón"));
	list.add(new Municipio("50072", "Carenas"));
	list.add(new Municipio("50073", "Cariñena"));
	list.add(new Municipio("50074", "Caspe"));
	list.add(new Municipio("50075", "Castejón de Alarba"));
	list.add(new Municipio("50076", "Castejón de las Armas"));
	list.add(new Municipio("50077", "Castejón de Valdejasa"));
	list.add(new Municipio("50078", "Castiliscar"));
	list.add(new Municipio("50079", "Cervera de la Cañada"));
	list.add(new Municipio("50080", "Cerveruela"));
	list.add(new Municipio("50081", "Cetina"));
	list.add(new Municipio("50092", "Chiprana"));
	list.add(new Municipio("50093", "Chodes"));
	list.add(new Municipio("50082", "Cimballa"));
	list.add(new Municipio("50083", "Cinco Olivas"));
	list.add(new Municipio("50084", "Clarés de Ribota"));
	list.add(new Municipio("50085", "Codo"));
	list.add(new Municipio("50086", "Codos"));
	list.add(new Municipio("50087", "Contamina"));
	list.add(new Municipio("50088", "Cosuenda"));
	list.add(new Municipio("50089", "Cuarte de Huerva"));
	list.add(new Municipio("50090", "Cubel"));
	list.add(new Municipio("50091", "Cuerlas, Las"));
	list.add(new Municipio("50094", "Daroca"));
	list.add(new Municipio("50095", "Ejea de los Caballeros"));
	list.add(new Municipio("50096", "Embid de Ariza"));
	list.add(new Municipio("50098", "Encinacorba"));
	list.add(new Municipio("50099", "Épila"));
	list.add(new Municipio("50100", "Erla"));
	list.add(new Municipio("50101", "Escatrón"));
	list.add(new Municipio("50102", "Fabara"));
	list.add(new Municipio("50104", "Farlete"));
	list.add(new Municipio("50105", "Fayón"));
	list.add(new Municipio("50106", "Fayos, Los"));
	list.add(new Municipio("50107", "Figueruelas"));
	list.add(new Municipio("50108", "Fombuena"));
	list.add(new Municipio("50109", "Frago, El"));
	list.add(new Municipio("50110", "Frasno, El"));
	list.add(new Municipio("50111", "Fréscano"));
	list.add(new Municipio("50113", "Fuendejalón"));
	list.add(new Municipio("50114", "Fuendetodos"));
	list.add(new Municipio("50115", "Fuentes de Ebro"));
	list.add(new Municipio("50116", "Fuentes de Jiloca"));
	list.add(new Municipio("50117", "Gallocanta"));
	list.add(new Municipio("50118", "Gallur"));
	list.add(new Municipio("50119", "Gelsa"));
	list.add(new Municipio("50120", "Godojos"));
	list.add(new Municipio("50121", "Gotor"));
	list.add(new Municipio("50122", "Grisel"));
	list.add(new Municipio("50123", "Grisén"));
	list.add(new Municipio("50124", "Herrera de los Navarros"));
	list.add(new Municipio("50125", "Ibdes"));
	list.add(new Municipio("50126", "Illueca"));
	list.add(new Municipio("50128", "Isuerre"));
	list.add(new Municipio("50129", "Jaraba"));
	list.add(new Municipio("50130", "Jarque"));
	list.add(new Municipio("50131", "Jaulín"));
	list.add(new Municipio("50132", "Joyosa, La"));
	list.add(new Municipio("50133", "Lagata"));
	list.add(new Municipio("50134", "Langa del Castillo"));
	list.add(new Municipio("50135", "Layana"));
	list.add(new Municipio("50136", "Lécera"));
	list.add(new Municipio("50138", "Lechón"));
	list.add(new Municipio("50137", "Leciñena"));
	list.add(new Municipio("50139", "Letux"));
	list.add(new Municipio("50140", "Litago"));
	list.add(new Municipio("50141", "Lituénigo"));
	list.add(new Municipio("50142", "Lobera de Onsella"));
	list.add(new Municipio("50143", "Longares"));
	list.add(new Municipio("50144", "Longás"));
	list.add(new Municipio("50146", "Lucena de Jalón"));
	list.add(new Municipio("50147", "Luceni"));
	list.add(new Municipio("50148", "Luesia"));
	list.add(new Municipio("50149", "Luesma"));
	list.add(new Municipio("50150", "Lumpiaque"));
	list.add(new Municipio("50151", "Luna"));
	list.add(new Municipio("50152", "Maella"));
	list.add(new Municipio("50153", "Magallón"));
	list.add(new Municipio("50154", "Mainar"));
	list.add(new Municipio("50155", "Malanquilla"));
	list.add(new Municipio("50156", "Maleján"));
	list.add(new Municipio("50160", "Mallén"));
	list.add(new Municipio("50157", "Malón"));
	list.add(new Municipio("50159", "Maluenda"));
	list.add(new Municipio("50161", "Manchones"));
	list.add(new Municipio("50162", "Mara"));
	list.add(new Municipio("50163", "María de Huerva"));
	list.add(new Municipio("50902", "Marracos"));
	list.add(new Municipio("50164", "Mediana de Aragón"));
	list.add(new Municipio("50165", "Mequinenza"));
	list.add(new Municipio("50166", "Mesones de Isuela"));
	list.add(new Municipio("50167", "Mezalocha"));
	list.add(new Municipio("50168", "Mianos"));
	list.add(new Municipio("50169", "Miedes de Aragón"));
	list.add(new Municipio("50170", "Monegrillo"));
	list.add(new Municipio("50171", "Moneva"));
	list.add(new Municipio("50172", "Monreal de Ariza"));
	list.add(new Municipio("50173", "Monterde"));
	list.add(new Municipio("50174", "Montón"));
	list.add(new Municipio("50175", "Morata de Jalón"));
	list.add(new Municipio("50176", "Morata de Jiloca"));
	list.add(new Municipio("50177", "Morés"));
	list.add(new Municipio("50178", "Moros"));
	list.add(new Municipio("50179", "Moyuela"));
	list.add(new Municipio("50180", "Mozota"));
	list.add(new Municipio("50181", "Muel"));
	list.add(new Municipio("50182", "Muela, La"));
	list.add(new Municipio("50183", "Munébrega"));
	list.add(new Municipio("50184", "Murero"));
	list.add(new Municipio("50185", "Murillo de Gállego"));
	list.add(new Municipio("50186", "Navardún"));
	list.add(new Municipio("50187", "Nigüella"));
	list.add(new Municipio("50188", "Nombrevilla"));
	list.add(new Municipio("50189", "Nonaspe"));
	list.add(new Municipio("50190", "Novallas"));
	list.add(new Municipio("50191", "Novillas"));
	list.add(new Municipio("50192", "Nuévalos"));
	list.add(new Municipio("50193", "Nuez de Ebro"));
	list.add(new Municipio("50194", "Olvés"));
	list.add(new Municipio("50195", "Orcajo"));
	list.add(new Municipio("50196", "Orera"));
	list.add(new Municipio("50197", "Orés"));
	list.add(new Municipio("50198", "Oseja"));
	list.add(new Municipio("50199", "Osera de Ebro"));
	list.add(new Municipio("50200", "Paniza"));
	list.add(new Municipio("50201", "Paracuellos de Jiloca"));
	list.add(new Municipio("50202", "Paracuellos de la Ribera"));
	list.add(new Municipio("50203", "Pastriz"));
	list.add(new Municipio("50204", "Pedrola"));
	list.add(new Municipio("50205", "Pedrosas, Las"));
	list.add(new Municipio("50206", "Perdiguera"));
	list.add(new Municipio("50207", "Piedratajada"));
	list.add(new Municipio("50208", "Pina de Ebro"));
	list.add(new Municipio("50209", "Pinseque"));
	list.add(new Municipio("50210", "Pintanos, Los"));
	list.add(new Municipio("50211", "Plasencia de Jalón"));
	list.add(new Municipio("50212", "Pleitas"));
	list.add(new Municipio("50213", "Plenas"));
	list.add(new Municipio("50214", "Pomer"));
	list.add(new Municipio("50215", "Pozuel de Ariza"));
	list.add(new Municipio("50216", "Pozuelo de Aragón"));
	list.add(new Municipio("50217", "Pradilla de Ebro"));
	list.add(new Municipio("50218", "Puebla de Albortón"));
	list.add(new Municipio("50219", "Puebla de Alfindén, La"));
	list.add(new Municipio("50220", "Puendeluna"));
	list.add(new Municipio("50221", "Purujosa"));
	list.add(new Municipio("50222", "Quinto"));
	list.add(new Municipio("50223", "Remolinos"));
	list.add(new Municipio("50224", "Retascón"));
	list.add(new Municipio("50225", "Ricla"));
	list.add(new Municipio("50227", "Romanos"));
	list.add(new Municipio("50228", "Rueda de Jalón"));
	list.add(new Municipio("50229", "Ruesca"));
	list.add(new Municipio("50241", "Sabiñán"));
	list.add(new Municipio("50230", "Sádaba"));
	list.add(new Municipio("50231", "Salillas de Jalón"));
	list.add(new Municipio("50232", "Salvatierra de Esca"));
	list.add(new Municipio("50233", "Samper del Salz"));
	list.add(new Municipio("50234", "San Martín de la Virgen de Moncayo"));
	list.add(new Municipio("50235", "San Mateo de Gállego"));
	list.add(new Municipio("50236", "Santa Cruz de Grío"));
	list.add(new Municipio("50237", "Santa Cruz de Moncayo"));
	list.add(new Municipio("50238", "Santa Eulalia de Gállego"));
	list.add(new Municipio("50239", "Santed"));
	list.add(new Municipio("50240", "Sástago"));
	list.add(new Municipio("50242", "Sediles"));
	list.add(new Municipio("50243", "Sestrica"));
	list.add(new Municipio("50244", "Sierra de Luna"));
	list.add(new Municipio("50245", "Sigüés"));
	list.add(new Municipio("50246", "Sisamón"));
	list.add(new Municipio("50247", "Sobradiel"));
	list.add(new Municipio("50248", "Sos del Rey Católico"));
	list.add(new Municipio("50249", "Tabuenca"));
	list.add(new Municipio("50250", "Talamantes"));
	list.add(new Municipio("50251", "Tarazona"));
	list.add(new Municipio("50252", "Tauste"));
	list.add(new Municipio("50253", "Terrer"));
	list.add(new Municipio("50254", "Tierga"));
	list.add(new Municipio("50255", "Tobed"));
	list.add(new Municipio("50256", "Torralba de los Frailes"));
	list.add(new Municipio("50257", "Torralba de Ribota"));
	list.add(new Municipio("50258", "Torralbilla"));
	list.add(new Municipio("50259", "Torrehermosa"));
	list.add(new Municipio("50260", "Torrelapaja"));
	list.add(new Municipio("50261", "Torrellas"));
	list.add(new Municipio("50262", "Torres de Berrellén"));
	list.add(new Municipio("50263", "Torrijo de la Cañada"));
	list.add(new Municipio("50264", "Tosos"));
	list.add(new Municipio("50265", "Trasmoz"));
	list.add(new Municipio("50266", "Trasobares"));
	list.add(new Municipio("50267", "Uncastillo"));
	list.add(new Municipio("50268", "Undués de Lerda"));
	list.add(new Municipio("50269", "Urrea de Jalón"));
	list.add(new Municipio("50270", "Urriés"));
	list.add(new Municipio("50271", "Used"));
	list.add(new Municipio("50272", "Utebo"));
	list.add(new Municipio("50274", "Val de San Martín"));
	list.add(new Municipio("50273", "Valdehorna"));
	list.add(new Municipio("50275", "Valmadrid"));
	list.add(new Municipio("50276", "Valpalmas"));
	list.add(new Municipio("50277", "Valtorres"));
	list.add(new Municipio("50278", "Velilla de Ebro"));
	list.add(new Municipio("50279", "Velilla de Jiloca"));
	list.add(new Municipio("50280", "Vera de Moncayo"));
	list.add(new Municipio("50281", "Vierlas"));
	list.add(new Municipio("50283", "Villadoz"));
	list.add(new Municipio("50284", "Villafeliche"));
	list.add(new Municipio("50285", "Villafranca de Ebro"));
	list.add(new Municipio("50286", "Villalba de Perejil"));
	list.add(new Municipio("50287", "Villalengua"));
	list.add(new Municipio("50903", "Villamayor de Gállego"));
	list.add(new Municipio("50288", "Villanueva de Gállego"));
	list.add(new Municipio("50290", "Villanueva de Huerva"));
	list.add(new Municipio("50289", "Villanueva de Jiloca"));
	list.add(new Municipio("50291", "Villar de los Navarros"));
	list.add(new Municipio("50292", "Villarreal de Huerva"));
	list.add(new Municipio("50293", "Villarroya de la Sierra"));
	list.add(new Municipio("50294", "Villarroya del Campo"));
	list.add(new Municipio("50282", "Vilueña, La"));
	list.add(new Municipio("50295", "Vistabella"));
	list.add(new Municipio("50296", "Zaida, La"));
	list.add(new Municipio("50297", "Zaragoza"));
	list.add(new Municipio("50298", "Zuera"));

	return list;
    }
}
